### Contoh Code Python

In [5]:
for item in list_1:
    print(item)

1
2
3
4
5
6
7


In [4]:
list_1 = [1,2,3,4,5,6,7]

In [10]:
type(list_1)
list_1

[1, 2, 3, 4, 5, 6, 7]

In [7]:
import numpy as np


In [9]:
data_1

array([1, 2, 3, 4, 5, 6, 7])

In [18]:
data_1 = np.array(list_1)
type(data_1)
data_1.dtype

dtype('int32')

In [23]:
list_2 = [1, '2', 3.0]
list_2 = [float(x) for x in list_2]
list_2

[1.0, 2.0, 3.0]

In [25]:
data_2 = np.array(list_2)
data_2.dtype
data_2

array([1., 2., 3.])

### List >> nd Array

In [28]:
students = ['Ari', 'Ana', 'Rudi']
len(students)

3

In [33]:
# for student in range(len(students)):
#     print(students[student])
for student in students:
    print(student)

Ari
Ana
Rudi


In [41]:
exam_result = [{'name': 'Ari', 'result': 3.7}, {'name': 'Ana', 'result': 7.7},{'name': 'rudi', 'result': 6.8},]

In [36]:
for item_result in exam_result:
    print(item_result)

{'name': 'Ari', 'result': 8.7}
{'name': 'Ana', 'result': 7.7}
{'name': 'rudi', 'result': 6.8}


In [43]:
for item_result in exam_result:
    name = item_result['name']
    result = item_result['result']
    lulus = 'Lulus'
    if result<=6.5:
        lulus = 'Tidak lulus'
    print(f'Peserta dengan nama {name} mendapat nilai {result} dan dinyatakan {lulus}.')

Peserta dengan nama Ari mendapat nilai 3.7 dan dinyatakan Tidak lulus.
Peserta dengan nama Ana mendapat nilai 7.7 dan dinyatakan Lulus.
Peserta dengan nama rudi mendapat nilai 6.8 dan dinyatakan Lulus.


## Slicing Array

In [47]:
list_3 =[1,2,3,4,5,6,7,8]
list_3

[1, 2, 3, 4, 5, 6, 7, 8]

In [45]:
list_4 = [[1,2],[3,4]]
list_4

[[1, 2], [3, 4]]

In [48]:
data_4 = np.array(list_4)
data_4

array([[1, 2],
       [3, 4]])

In [53]:
data_4[0,1]

2

In [62]:
list_5 = [x for x in range(16)]
list_5

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [63]:
data_5 = np.array(list_5).reshape(4,4)
data_5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [64]:
list_3

[1, 2, 3, 4, 5, 6, 7, 8]

In [71]:
list_3[1:4]

[2, 3, 4]

In [74]:
list_3[3:]

[4, 5, 6, 7, 8]

In [76]:
list_3[:5]

[1, 2, 3, 4, 5]

In [77]:
list_3[:]

[1, 2, 3, 4, 5, 6, 7, 8]

In [72]:
for i in range(len(list_3)):
    if i>=1 and i<4:
        print(list_3[i])

2
3
4


### Multidimension slicing

In [78]:
data_5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [80]:
# data 6
# sebelum koma',' untuk indeks baris dan setelah koma indeks untuk kolom
data_5[1,2]

6

In [84]:
# ambil kolom ke 3 [2,6,10,14]
data_5[:,2]

array([ 2,  6, 10, 14])

In [86]:
#ambil baris ke 2 [ 4,  5,  6,  7]
data_5[1,:]

array([4, 5, 6, 7])